// Pins.cs: the SIZE / AT / PIN lines of tests/abi_v1.c, tests/abi_storage.c, tests/abi_ui.c,
// tests/abi_datacore.c, tests/abi_game_actors.c, tests/abi_game_vehicles.c and tests/abi_game_entities.c, copied so the test runs from the SDK zip, where tests/ isn't shipped. Given
// those files on the command line, the test also fails unless this copy equals them line for line.
//
// Part of the sco SDK. GPL-3.0, like sco-core.
namespace Sco.Sdk.Tests
{
    internal static class Pins
    {
        public static readonly (string File, string Line)[] Lines =
        {
            ("tests/abi_v1.c", "PIN(sizeof(void*) == 8);"),
            ("tests/abi_v1.c", "PIN(sizeof(void (*)(void)) == 8);"),
            ("tests/abi_v1.c", "PIN(SCO_API_MAJOR == 1);"),
            ("tests/abi_v1.c", "PIN(SCO_API_MINOR == 1);"),
            ("tests/abi_v1.c", "SIZE(sco_result, 4);"),
            ("tests/abi_v1.c", "PIN(SCO_OK == 0);"),
            ("tests/abi_v1.c", "PIN(SCO_UNAVAILABLE == 1);"),
            ("tests/abi_v1.c", "PIN(SCO_NOT_FOUND == 2);"),
            ("tests/abi_v1.c", "PIN(SCO_BAD_ARG == 3);"),
            ("tests/abi_v1.c", "PIN(SCO_CRASHED == 4);"),
            ("tests/abi_v1.c", "PIN(SCO_WRONG_THREAD == 5);"),
            ("tests/abi_v1.c", "PIN(SCO_TOO_MANY == 6);"),
            ("tests/abi_v1.c", "PIN(SCO_FAILED == 7);"),
            ("tests/abi_v1.c", "PIN(SCO_RESULT_FORCE32 == 0x7fffffff);"),
            ("tests/abi_v1.c", "SIZE(sco_log_level, 4);"),
            ("tests/abi_v1.c", "PIN(SCO_LOG_INFO == 0);"),
            ("tests/abi_v1.c", "PIN(SCO_LOG_WARN == 1);"),
            ("tests/abi_v1.c", "PIN(SCO_LOG_ERROR == 2);"),
            ("tests/abi_v1.c", "PIN(SCO_LOG_FORCE32 == 0x7fffffff);"),
            ("tests/abi_v1.c", "SIZE(sco_arg_type, 4);"),
            ("tests/abi_v1.c", "PIN(SCO_ARG_INT == 0);"),
            ("tests/abi_v1.c", "PIN(SCO_ARG_FLOAT == 1);"),
            ("tests/abi_v1.c", "PIN(SCO_ARG_STRING == 2);"),
            ("tests/abi_v1.c", "PIN(SCO_ARG_BOOL == 3);"),
            ("tests/abi_v1.c", "PIN(SCO_ARG_FORCE32 == 0x7fffffff);"),
            ("tests/abi_v1.c", "SIZE(sco_arg, 16);"),
            ("tests/abi_v1.c", "AT(sco_arg, type, 0);"),
            ("tests/abi_v1.c", "AT(sco_arg, _pad, 4);"),
            ("tests/abi_v1.c", "AT(sco_arg, v, 8);"),
            ("tests/abi_v1.c", "AT(sco_arg, v.i, 8);"),
            ("tests/abi_v1.c", "AT(sco_arg, v.f, 8);"),
            ("tests/abi_v1.c", "AT(sco_arg, v.s, 8);"),
            ("tests/abi_v1.c", "SIZE(sco_arg_def, 24);"),
            ("tests/abi_v1.c", "AT(sco_arg_def, name, 0);"),
            ("tests/abi_v1.c", "AT(sco_arg_def, type, 8);"),
            ("tests/abi_v1.c", "AT(sco_arg_def, _pad, 12);"),
            ("tests/abi_v1.c", "AT(sco_arg_def, help, 16);"),
            ("tests/abi_v1.c", "SIZE(sco_command, 72);"),
            ("tests/abi_v1.c", "AT(sco_command, size, 0);"),
            ("tests/abi_v1.c", "AT(sco_command, _pad0, 4);"),
            ("tests/abi_v1.c", "AT(sco_command, name, 8);"),
            ("tests/abi_v1.c", "AT(sco_command, title, 16);"),
            ("tests/abi_v1.c", "AT(sco_command, help, 24);"),
            ("tests/abi_v1.c", "AT(sco_command, capability, 32);"),
            ("tests/abi_v1.c", "AT(sco_command, args, 40);"),
            ("tests/abi_v1.c", "AT(sco_command, nargs, 48);"),
            ("tests/abi_v1.c", "AT(sco_command, arg_def_size, 52);"),
            ("tests/abi_v1.c", "AT(sco_command, fn, 56);"),
            ("tests/abi_v1.c", "AT(sco_command, ctx, 64);"),
            ("tests/abi_v1.c", "SIZE(sco_api, 128);"),
            ("tests/abi_v1.c", "AT(sco_api, size, 0);"),
            ("tests/abi_v1.c", "AT(sco_api, major, 4);"),
            ("tests/abi_v1.c", "AT(sco_api, minor, 6);"),
            ("tests/abi_v1.c", "AT(sco_api, host_version, 8);"),
            ("tests/abi_v1.c", "AT(sco_api, has, 16);"),
            ("tests/abi_v1.c", "AT(sco_api, run_on_game_thread, 24);"),
            ("tests/abi_v1.c", "AT(sco_api, subscribe, 32);"),
            ("tests/abi_v1.c", "AT(sco_api, unsubscribe, 40);"),
            ("tests/abi_v1.c", "AT(sco_api, status, 48);"),
            ("tests/abi_v1.c", "AT(sco_api, log, 56);"),
            ("tests/abi_v1.c", "AT(sco_api, register_command, 64);"),
            ("tests/abi_v1.c", "AT(sco_api, invoke, 72);"),
            ("tests/abi_v1.c", "AT(sco_api, list_commands, 80);"),
            ("tests/abi_v1.c", "AT(sco_api, provide_service, 88);"),
            ("tests/abi_v1.c", "AT(sco_api, query_service, 96);"),
            ("tests/abi_v1.c", "AT(sco_api, release_service, 104);"),
            ("tests/abi_v1.c", "AT(sco_api, invoke_raw, 112);"),
            ("tests/abi_v1.c", "AT(sco_api, register_raw, 120);"),
            ("tests/abi_v1.c", "SIZE(sco_plugin_info, 32);"),
            ("tests/abi_v1.c", "AT(sco_plugin_info, size, 0);"),
            ("tests/abi_v1.c", "AT(sco_plugin_info, api_major, 4);"),
            ("tests/abi_v1.c", "AT(sco_plugin_info, api_minor, 6);"),
            ("tests/abi_v1.c", "AT(sco_plugin_info, name, 8);"),
            ("tests/abi_v1.c", "AT(sco_plugin_info, version, 16);"),
            ("tests/abi_v1.c", "AT(sco_plugin_info, author, 24);"),
            ("tests/abi_storage.c", "PIN(sizeof(void*) == 8);"),
            ("tests/abi_storage.c", "PIN(SCO_STORAGE_VERSION_1_0 == 0x00010000u);"),
            ("tests/abi_storage.c", "PIN(SCO_STORAGE_MAX_KEY == 255u);"),
            ("tests/abi_storage.c", "PIN(SCO_STORAGE_MAX_VALUE == 1048576u);"),
            ("tests/abi_storage.c", "PIN(SCO_STORAGE_MAX_CURSORS == 64u);"),
            ("tests/abi_storage.c", "PIN(sizeof(SCO_STORAGE_NAME) == 12); /* \"sco.storage\" */"),
            ("tests/abi_storage.c", "SIZE(sco_sql_type, 4);"),
            ("tests/abi_storage.c", "PIN(SCO_SQL_NULL == 0);"),
            ("tests/abi_storage.c", "PIN(SCO_SQL_INT == 1);"),
            ("tests/abi_storage.c", "PIN(SCO_SQL_FLOAT == 2);"),
            ("tests/abi_storage.c", "PIN(SCO_SQL_TEXT == 3);"),
            ("tests/abi_storage.c", "PIN(SCO_SQL_BLOB == 4);"),
            ("tests/abi_storage.c", "PIN(SCO_SQL_TYPE_FORCE32 == 0x7fffffff);"),
            ("tests/abi_storage.c", "SIZE(sco_sql_value, 16);"),
            ("tests/abi_storage.c", "AT(sco_sql_value, type, 0);"),
            ("tests/abi_storage.c", "AT(sco_sql_value, size, 4);"),
            ("tests/abi_storage.c", "AT(sco_sql_value, v, 8);"),
            ("tests/abi_storage.c", "AT(sco_sql_value, v.i, 8);"),
            ("tests/abi_storage.c", "AT(sco_sql_value, v.f, 8);"),
            ("tests/abi_storage.c", "AT(sco_sql_value, v.p, 8);"),
            ("tests/abi_storage.c", "SIZE(sco_storage_v1, 128);"),
            ("tests/abi_storage.c", "AT(sco_storage_v1, size, 0);"),
            ("tests/abi_storage.c", "AT(sco_storage_v1, _pad, 4);"),
            ("tests/abi_storage.c", "AT(sco_storage_v1, put, 8);"),
            ("tests/abi_storage.c", "AT(sco_storage_v1, get, 16);"),
            ("tests/abi_storage.c", "AT(sco_storage_v1, del, 24);"),
            ("tests/abi_storage.c", "AT(sco_storage_v1, next_key, 32);"),
            ("tests/abi_storage.c", "AT(sco_storage_v1, begin, 40);"),
            ("tests/abi_storage.c", "AT(sco_storage_v1, commit, 48);"),
            ("tests/abi_storage.c", "AT(sco_storage_v1, rollback, 56);"),
            ("tests/abi_storage.c", "AT(sco_storage_v1, exec, 64);"),
            ("tests/abi_storage.c", "AT(sco_storage_v1, query, 72);"),
            ("tests/abi_storage.c", "AT(sco_storage_v1, step, 80);"),
            ("tests/abi_storage.c", "AT(sco_storage_v1, column_count, 88);"),
            ("tests/abi_storage.c", "AT(sco_storage_v1, column, 96);"),
            ("tests/abi_storage.c", "AT(sco_storage_v1, column_name, 104);"),
            ("tests/abi_storage.c", "AT(sco_storage_v1, close, 112);"),
            ("tests/abi_storage.c", "AT(sco_storage_v1, last_error, 120);"),
            ("tests/abi_ui.c", "PIN(sizeof(void*) == 8);"),
            ("tests/abi_ui.c", "PIN(SCO_UI_VERSION_1_0 == 0x00010000u);"),
            ("tests/abi_ui.c", "PIN(sizeof(SCO_UI_NAME) == 7); /* \"sco.ui\" */"),
            ("tests/abi_ui.c", "PIN(SCO_UI_MAX_ID == 63u);"),
            ("tests/abi_ui.c", "PIN(SCO_UI_MAX_TITLE == 63u);"),
            ("tests/abi_ui.c", "PIN(SCO_UI_MAX_BADGE == 15u);"),
            ("tests/abi_ui.c", "PIN(SCO_UI_MAX_CHORD == 31u);"),
            ("tests/abi_ui.c", "PIN(SCO_UI_MAX_HOTKEY_ARGS == 16u);"),
            ("tests/abi_ui.c", "PIN(SCO_UI_MAX_ARG_STRING == 255u);"),
            ("tests/abi_ui.c", "SIZE(sco_ui_v1, 80);"),
            ("tests/abi_ui.c", "AT(sco_ui_v1, size, 0);"),
            ("tests/abi_ui.c", "AT(sco_ui_v1, _pad, 4);"),
            ("tests/abi_ui.c", "AT(sco_ui_v1, register_tab, 8);"),
            ("tests/abi_ui.c", "AT(sco_ui_v1, unregister_tab, 16);"),
            ("tests/abi_ui.c", "AT(sco_ui_v1, set_badge, 24);"),
            ("tests/abi_ui.c", "AT(sco_ui_v1, register_overlay, 32);"),
            ("tests/abi_ui.c", "AT(sco_ui_v1, unregister_overlay, 40);"),
            ("tests/abi_ui.c", "AT(sco_ui_v1, bind_hotkey, 48);"),
            ("tests/abi_ui.c", "AT(sco_ui_v1, unbind_hotkey, 56);"),
            ("tests/abi_ui.c", "AT(sco_ui_v1, normalize_chord, 64);"),
            ("tests/abi_ui.c", "AT(sco_ui_v1, last_error, 72);"),
            ("tests/abi_datacore.c", "PIN(sizeof(void*) == 8);"),
            ("tests/abi_datacore.c", "PIN(SCO_DATACORE_VERSION_1_0 == 0x00010000u);"),
            ("tests/abi_datacore.c", "PIN(SCO_DATACORE_VERSION_1_1 == 0x00010001u);"),
            ("tests/abi_datacore.c", "PIN(sizeof(SCO_DATACORE_NAME) == 13); /* \"sco.datacore\" */"),
            ("tests/abi_datacore.c", "PIN(sizeof(SCO_DC_APPLIED_EVENT) == 17); /* \"datacore.applied\" */"),
            ("tests/abi_datacore.c", "PIN(SCO_DC_OPEN == 1u);"),
            ("tests/abi_datacore.c", "PIN(SCO_DC_LOADED == 2u);"),
            ("tests/abi_datacore.c", "PIN(SCO_DC_NON_ATOMIC == 1u);"),
            ("tests/abi_datacore.c", "PIN(SCO_DC_QUEUED == 1u);"),
            ("tests/abi_datacore.c", "PIN(SCO_DC_APPLIED == 2u);"),
            ("tests/abi_datacore.c", "PIN(SCO_DC_SKIPPED == 3u);"),
            ("tests/abi_datacore.c", "PIN(SCO_DC_REFUSED == 4u);"),
            ("tests/abi_datacore.c", "PIN(SCO_DC_OP_PATCH == 0xFFFFFFFFu);"),
            ("tests/abi_datacore.c", "PIN(SCO_DC_MAX_OPS == 65536u);"),
            ("tests/abi_datacore.c", "PIN(SCO_DC_MAX_PATCHES == 64u);"),
            ("tests/abi_datacore.c", "SIZE(sco_dc_type, 4);"),
            ("tests/abi_datacore.c", "PIN(SCO_DC_BOOL == 0);"),
            ("tests/abi_datacore.c", "PIN(SCO_DC_INT == 1);"),
            ("tests/abi_datacore.c", "PIN(SCO_DC_UINT == 2);"),
            ("tests/abi_datacore.c", "PIN(SCO_DC_FLOAT == 3);"),
            ("tests/abi_datacore.c", "PIN(SCO_DC_STRING == 4);"),
            ("tests/abi_datacore.c", "PIN(SCO_DC_GUID == 5);"),
            ("tests/abi_datacore.c", "PIN(SCO_DC_ENUM == 6);"),
            ("tests/abi_datacore.c", "PIN(SCO_DC_NULL == 7);"),
            ("tests/abi_datacore.c", "PIN(SCO_DC_INSTANCE == 8);"),
            ("tests/abi_datacore.c", "PIN(SCO_DC_REF == 9);"),
            ("tests/abi_datacore.c", "PIN(SCO_DC_TYPE_FORCE32 == 0x7fffffff);"),
            ("tests/abi_datacore.c", "SIZE(sco_dc_value, 40);"),
            ("tests/abi_datacore.c", "AT(sco_dc_value, size, 0);"),
            ("tests/abi_datacore.c", "AT(sco_dc_value, type, 4);"),
            ("tests/abi_datacore.c", "AT(sco_dc_value, i, 8);"),
            ("tests/abi_datacore.c", "AT(sco_dc_value, u, 16);"),
            ("tests/abi_datacore.c", "AT(sco_dc_value, f, 24);"),
            ("tests/abi_datacore.c", "AT(sco_dc_value, s, 32);"),
            ("tests/abi_datacore.c", "SIZE(sco_dc_report, 204);"),
            ("tests/abi_datacore.c", "AT(sco_dc_report, size, 0);"),
            ("tests/abi_datacore.c", "AT(sco_dc_report, state, 4);"),
            ("tests/abi_datacore.c", "AT(sco_dc_report, op_index, 8);"),
            ("tests/abi_datacore.c", "AT(sco_dc_report, reason, 12);"),
            ("tests/abi_datacore.c", "SIZE(sco_dc_applied, 16);"),
            ("tests/abi_datacore.c", "AT(sco_dc_applied, size, 0);"),
            ("tests/abi_datacore.c", "AT(sco_dc_applied, applied, 4);"),
            ("tests/abi_datacore.c", "AT(sco_dc_applied, skipped, 8);"),
            ("tests/abi_datacore.c", "AT(sco_dc_applied, refused, 12);"),
            ("tests/abi_datacore.c", "SIZE(sco_datacore_v1, 88);"),
            ("tests/abi_datacore.c", "AT(sco_datacore_v1, size, 0);"),
            ("tests/abi_datacore.c", "AT(sco_datacore_v1, _pad, 4);"),
            ("tests/abi_datacore.c", "AT(sco_datacore_v1, state, 8);"),
            ("tests/abi_datacore.c", "AT(sco_datacore_v1, begin, 16);"),
            ("tests/abi_datacore.c", "AT(sco_datacore_v1, set, 24);"),
            ("tests/abi_datacore.c", "AT(sco_datacore_v1, add_instance, 32);"),
            ("tests/abi_datacore.c", "AT(sco_datacore_v1, set_pointer, 40);"),
            ("tests/abi_datacore.c", "AT(sco_datacore_v1, append, 48);"),
            ("tests/abi_datacore.c", "AT(sco_datacore_v1, add_record, 56);"),
            ("tests/abi_datacore.c", "AT(sco_datacore_v1, commit, 64);"),
            ("tests/abi_datacore.c", "AT(sco_datacore_v1, discard, 72);"),
            ("tests/abi_datacore.c", "AT(sco_datacore_v1, report, 80);"),
            ("tests/abi_game_actors.c", "PIN(sizeof(void*) == 8);"),
            ("tests/abi_game_actors.c", "PIN(SC_ACTORS_VERSION_1_0 == 0x00010000u);"),
            ("tests/abi_game_actors.c", "PIN(sizeof(SC_ACTORS_NAME) == 12); /* \"game.actors\" */"),
            ("tests/abi_game_actors.c", "PIN(SC_ACTORS_MAX_NPCS == 1024u);"),
            ("tests/abi_game_actors.c", "SIZE(sc_actors_v1, 40);"),
            ("tests/abi_game_actors.c", "AT(sc_actors_v1, size, 0);"),
            ("tests/abi_game_actors.c", "AT(sc_actors_v1, _pad, 4);"),
            ("tests/abi_game_actors.c", "AT(sc_actors_v1, local_player, 8);"),
            ("tests/abi_game_actors.c", "AT(sc_actors_v1, spawn_npc, 16);"),
            ("tests/abi_game_actors.c", "AT(sc_actors_v1, despawn, 24);"),
            ("tests/abi_game_actors.c", "AT(sc_actors_v1, last_error, 32);"),
            ("tests/abi_game_vehicles.c", "PIN(sizeof(void*) == 8);"),
            ("tests/abi_game_vehicles.c", "PIN(SC_VEHICLES_SERVICE_VERSION == 0x00010000u);"),
            ("tests/abi_game_vehicles.c", "PIN(sizeof(SC_VEHICLES_SERVICE_NAME) == 14); /* \"game.vehicles\" */"),
            ("tests/abi_game_vehicles.c", "PIN(SC_VEHICLE_SEAT_NAME_MAX == 64);"),
            ("tests/abi_game_vehicles.c", "SIZE(sc_vehicle_seat_flag, 4);"),
            ("tests/abi_game_vehicles.c", "PIN(SC_SEAT_USABLE == 0x1);"),
            ("tests/abi_game_vehicles.c", "PIN(SC_SEAT_USABLE_KNOWN == 0x2);"),
            ("tests/abi_game_vehicles.c", "PIN(SC_SEAT_OCCUPIED == 0x4);"),
            ("tests/abi_game_vehicles.c", "PIN(SC_SEAT_PILOT == 0x8);"),
            ("tests/abi_game_vehicles.c", "PIN(SC_SEAT_FLAG_FORCE32 == 0x7fffffff);"),
            ("tests/abi_game_vehicles.c", "SIZE(sc_vehicle_seat, 96);"),
            ("tests/abi_game_vehicles.c", "AT(sc_vehicle_seat, index, 0);"),
            ("tests/abi_game_vehicles.c", "AT(sc_vehicle_seat, flags, 4);"),
            ("tests/abi_game_vehicles.c", "AT(sc_vehicle_seat, seat_id, 8);"),
            ("tests/abi_game_vehicles.c", "AT(sc_vehicle_seat, occupant_id, 16);"),
            ("tests/abi_game_vehicles.c", "AT(sc_vehicle_seat, priority, 24);"),
            ("tests/abi_game_vehicles.c", "AT(sc_vehicle_seat, _pad, 28);"),
            ("tests/abi_game_vehicles.c", "AT(sc_vehicle_seat, name, 32);"),
            ("tests/abi_game_vehicles.c", "SIZE(sc_vehicles_v1, 64);"),
            ("tests/abi_game_vehicles.c", "AT(sc_vehicles_v1, size, 0);"),
            ("tests/abi_game_vehicles.c", "AT(sc_vehicles_v1, _pad, 4);"),
            ("tests/abi_game_vehicles.c", "AT(sc_vehicles_v1, player_ship, 8);"),
            ("tests/abi_game_vehicles.c", "AT(sc_vehicles_v1, seats, 16);"),
            ("tests/abi_game_vehicles.c", "AT(sc_vehicles_v1, seat_occupant, 24);"),
            ("tests/abi_game_vehicles.c", "AT(sc_vehicles_v1, seat, 32);"),
            ("tests/abi_game_vehicles.c", "AT(sc_vehicles_v1, eject, 40);"),
            ("tests/abi_game_vehicles.c", "AT(sc_vehicles_v1, power_on, 48);"),
            ("tests/abi_game_vehicles.c", "AT(sc_vehicles_v1, last_error, 56);"),
            ("tests/abi_game_entities.c", "PIN(sizeof(void*) == 8);"),
            ("tests/abi_game_entities.c", "PIN(SC_ENTITIES_VERSION_1_0 == 0x00010000u);"),
            ("tests/abi_game_entities.c", "PIN(sizeof(SC_ENTITIES_NAME) == 14); /* \"game.entities\" */"),
            ("tests/abi_game_entities.c", "PIN(SC_ENTITIES_MAX_OWNED == 1024u);"),
            ("tests/abi_game_entities.c", "PIN(SC_ENTITIES_MAX_WATCHES == 64u);"),
            ("tests/abi_game_entities.c", "PIN(SC_ENTITIES_MAX_TYPE_LEN == 63u);"),
            ("tests/abi_game_entities.c", "PIN(SC_ENTITY_STREAMED_IN == 1u);"),
            ("tests/abi_game_entities.c", "PIN(SC_ENTITY_STREAMED_OUT == 2u);"),
            ("tests/abi_game_entities.c", "SIZE(sc_entities_v1, 88);"),
            ("tests/abi_game_entities.c", "AT(sc_entities_v1, size, 0);"),
            ("tests/abi_game_entities.c", "AT(sc_entities_v1, _pad, 4);"),
            ("tests/abi_game_entities.c", "AT(sc_entities_v1, alive, 8);"),
            ("tests/abi_game_entities.c", "AT(sc_entities_v1, class_of, 16);"),
            ("tests/abi_game_entities.c", "AT(sc_entities_v1, get_transform, 24);"),
            ("tests/abi_game_entities.c", "AT(sc_entities_v1, set_transform, 32);"),
            ("tests/abi_game_entities.c", "AT(sc_entities_v1, spawn, 40);"),
            ("tests/abi_game_entities.c", "AT(sc_entities_v1, despawn, 48);"),
            ("tests/abi_game_entities.c", "AT(sc_entities_v1, watch, 56);"),
            ("tests/abi_game_entities.c", "AT(sc_entities_v1, unwatch, 64);"),
            ("tests/abi_game_entities.c", "AT(sc_entities_v1, query_radius, 72);"),
            ("tests/abi_game_entities.c", "AT(sc_entities_v1, last_error, 80);"),
        };
    }
}
